"""never

Revision ID: 18d463f4313f
Revises: b0b0a7c3fe50
Create Date: 2023-12-10 00:34:20.340936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d463f4313f'
down_revision = 'b0b0a7c3fe50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lots_history')
    op.add_column('lots', sa.Column('closed_bet', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'closed_bet')
    op.create_table('lots_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lots_history_pkey')
    )
    # ### end Alembic commands ###
