"""never

Revision ID: 576e5dbf5dc8
Revises: 840d2bae2230
Create Date: 2023-10-21 03:30:06.400250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '576e5dbf5dc8'
down_revision = '840d2bae2230'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('users', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'categories')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
