"""never

Revision ID: 840d2bae2230
Revises: f61bdf730a5e
Create Date: 2023-10-21 03:11:05.199515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840d2bae2230'
down_revision = 'f61bdf730a5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.Uuid(), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
