"""never

Revision ID: e89aa3916d37
Revises: 576e5dbf5dc8
Create Date: 2023-10-21 03:34:08.996110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89aa3916d37'
down_revision = '576e5dbf5dc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
