"""never

Revision ID: f61bdf730a5e
Revises: bd1a52be77ee
Create Date: 2023-10-21 03:07:44.434720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61bdf730a5e'
down_revision = 'bd1a52be77ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
